# Generated by Django 3.1 on 2022-03-29 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appone', '0001_initial'),
        ('apptwo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apptwo.car')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appone.model')),
            ],
        ),
    ]
